language: php

php:
    - "7.4"
    #- "8.0"

before_script:
    #- make install check
    - make install

script:
    - make test

env:
  - APP_ENV=dev
  - APP_SECRET=119f5d8cd8e007f1433df09efef9482c
